spring:
 datasource:
  url: jdbc:oracle:thin:@localhost:1521/orclpdb
  username: local_db
  password: jordan1993
 jpa:
  hibernate:
   ddl-auto: update
 show-sql: true
 properties:
  hibernate:
   format_sql: true
 
 redis:
  host: localhost
  port: 6379